Add experimental dialog callback
pypeclub/avalon-unreal-integration pull request #1
Opened 2021-11-29 19:26 UTC by iLLiCiTiT

## Changes
- removed project manager action (with System menu)
- removed unused workfiles tool action
- added new experimental dialog action

Depends on https://github.com/pypeclub/avalon-core/pull/395

2021-11-30 15:08 UTC, antirotor commented
this is missing Python implementation of `show_experimental_tools`

2021-11-30 15:40 UTC, antirotor requested changes
this is missing Python implementation of show_experimental_tools

2021-11-30 20:02 UTC, iLLiCiTiT commented
> this is missing Python implementation of show_experimental_tools

That's why `Depends on pypeclub/avalon-core#395` is there

2021-12-22 12:41 UTC, antirotor commented
Is this superceded by #3?

2021-12-22 12:51 UTC, antirotor commented
> Is this superceded by #3?

It is.

2021-12-22 12:51 UTC, closed without merging